
package com.oracle.xmlns.apps.crmcommon.salesparties.contactservice;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.xmlns.adf.svc.types.DataObjectResult;
import com.oracle.xmlns.adf.svc.types.FindControl;
import com.oracle.xmlns.adf.svc.types.FindCriteria;
import com.oracle.xmlns.adf.svc.types.MethodResult;
import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ProcessControl;
import com.oracle.xmlns.adf.svc.types.ProcessData;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactService", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/")
@XmlSeeAlso({
    com.oracle.xmlns.adf.svc.errors.ObjectFactory.class,
    com.oracle.xmlns.adf.svc.types.ObjectFactory.class,
    com.oracle.xmlns.apps.cdm.foundation.parties.personservice.ObjectFactory.class,
    com.oracle.xmlns.apps.crmcommon.notes.flex.notedff.ObjectFactory.class,
    com.oracle.xmlns.apps.crmcommon.notes.noteservice.ObjectFactory.class,
    com.oracle.xmlns.apps.crmcommon.salesparties.commonservice.ObjectFactory.class,
    com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.ObjectFactory.class,
    com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.ObjectFactory.class,
    com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class,
    sdo.commonj.ObjectFactory.class,
    sdo.commonj.java.ObjectFactory.class,
    sdo.commonj.xml.ObjectFactory.class
})
public interface ContactService {


    /**
     * 
     * @param processControl
     * @param processData
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ProcessData
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/processCSContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "processCSContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.ProcessCSContact")
    @ResponseWrapper(localName = "processCSContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.ProcessCSContactResponse")
    public ProcessData processCSContact(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param processData
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/processCSContactAsync")
    @Oneway
    @RequestWrapper(localName = "processCSContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.ProcessCSContactAsync")
    public void processCSContactAsync(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.xmlns.adf.svc.types.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param partyId
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "getContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetContact")
    @ResponseWrapper(localName = "getContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetContactResponse")
    public DataObjectResult getContact(
        @WebParam(name = "PartyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        long partyId)
        throws ServiceException
    ;

    /**
     * 
     * @param contact
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/createContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "createContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.CreateContact")
    @ResponseWrapper(localName = "createContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.CreateContactResponse")
    public DataObjectResult createContact(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact)
        throws ServiceException
    ;

    /**
     * 
     * @param contact
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/updateContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "updateContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.UpdateContact")
    @ResponseWrapper(localName = "updateContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.UpdateContactResponse")
    public DataObjectResult updateContact(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact)
        throws ServiceException
    ;

    /**
     * 
     * @param contact
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.MethodResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/deleteContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "deleteContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.DeleteContact")
    @ResponseWrapper(localName = "deleteContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.DeleteContactResponse")
    public MethodResult deleteContact(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact)
        throws ServiceException
    ;

    /**
     * 
     * @param contact
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/mergeContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "mergeContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.MergeContact")
    @ResponseWrapper(localName = "mergeContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.MergeContactResponse")
    public DataObjectResult mergeContact(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/findContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "findContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.FindContact")
    @ResponseWrapper(localName = "findContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.FindContactResponse")
    public DataObjectResult findContact(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param changeOperation
     * @param contact
     * @return
     *     returns com.oracle.xmlns.adf.svc.types.DataObjectResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/processContact")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
    @RequestWrapper(localName = "processContact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.ProcessContact")
    @ResponseWrapper(localName = "processContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.ProcessContactResponse")
    public DataObjectResult processContact(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        String changeOperation,
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        List<Contact> contact,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/findContactAsync")
    @Oneway
    @RequestWrapper(localName = "findContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.FindContactAsync")
    public void findContactAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        FindControl findControl);

    /**
     * 
     * @param contact
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/updateContactAsync")
    @Oneway
    @RequestWrapper(localName = "updateContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.UpdateContactAsync")
    public void updateContactAsync(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact);

    /**
     * 
     * @param processControl
     * @param changeOperation
     * @param contact
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/processContactAsync")
    @Oneway
    @RequestWrapper(localName = "processContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.ProcessContactAsync")
    public void processContactAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        String changeOperation,
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        List<Contact> contact,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param contact
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/createContactAsync")
    @Oneway
    @RequestWrapper(localName = "createContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.CreateContactAsync")
    public void createContactAsync(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact);

    /**
     * 
     * @param partyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/getContactAsync")
    @Oneway
    @RequestWrapper(localName = "getContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.GetContactAsync")
    public void getContactAsync(
        @WebParam(name = "PartyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        long partyId);

    /**
     * 
     * @param contact
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/mergeContactAsync")
    @Oneway
    @RequestWrapper(localName = "mergeContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.MergeContactAsync")
    public void mergeContactAsync(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact);

    /**
     * 
     * @param contact
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/deleteContactAsync")
    @Oneway
    @RequestWrapper(localName = "deleteContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/", className = "com.oracle.xmlns.apps.crmcommon.salesparties.contactservice.types.DeleteContactAsync")
    public void deleteContactAsync(
        @WebParam(name = "contact", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/contactService/types/")
        Contact contact);

}
